### ISSUE TITLE
change the alert boxes to modal boxes 

### ISSUE THREAD

**Issue by smaji08** [smaji08/CookOut#34]
- [Must use at least two server-side APIs]  **check**

- [Must use a CSS framework other than Bootstrap] **check**

- [ Must be interactive (i.e: accept and respond to user input)]   **check**

- [Use at least one new third-party] **check**

- [Must have a polished UI] **check**

- [Must meet good quality coding standards ] **check** ?

- [Does not use alerts, confirms or prompts (look into modals)]  _issue_

- [Must be deployed to GitHub Pages ]  **check**

**Comment by rnm-code-repo** [comment]
can you be more clear please? what alert boxes do we get and where.I do not see any alert boxes.
